version: '3'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: laravel_app_nginx
        ports:
        - "8989:80"
        volumes:
        - ./:/var/www/html
        - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
        - php
        - mysql
        networks:
        - laravel_app

    php:
      user: "${UID}:${GID}"
      build:
        context: .
        dockerfile: Dockerfile
      container_name: laravel_app_php
      restart: unless-stopped
      volumes:
        - ./:/var/www/html
      depends_on:
        - redis
      networks:
        - laravel_app

    mysql:
      image: mysql:5.7.22
      container_name: laravel_app_mysql
      restart: always
      ports:
        - "3308:3306"
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      volumes:
        - ./.mysql:/var/lib/mysql
      networks:
        - laravel_app

    npm:
      image: node:16.15.1
      container_name: laravel_app_npm
      volumes:
        - ./:/var/www/html
      working_dir: /var/www/html
      entrypoint: ['npm']

    redis:
      image: redis:latest
      container_name: laravel_app_redis
      ports:
        - "6380:6379"
      networks:
        - laravel_app

    sonarqube:
        container_name: laravel_app_sonarqube
        image: sonarqube:lts-community
        restart: unless-stopped
        ports:
            - "9001:9000"
        networks:
            - laravel_app

networks:
    laravel_app:
        driver: bridge

